"use strict";

// module KanColle.Expedition.New.Info

exports.kcExpeditionRaw =
    [
        {
            "api_id":1,
            "api_time":15,
            "api_use_fuel":0.3,
            "api_use_bull":0,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":2,
            "api_time":30,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[1,1],
            "api_win_item2":[0,0]
        },
        {
            "api_id":3,
            "api_time":20,
            "api_use_fuel":0.3,
            "api_use_bull":0.2,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":4,
            "api_time":50,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[1,1],
            "api_win_item2":[10,1]
        },
        {
            "api_id":5,
            "api_time":90,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":6,
            "api_time":40,
            "api_use_fuel":0.3,
            "api_use_bull":0.2,
            "api_win_item1":[10,1],
            "api_win_item2":[0,0]
        },
        {
            "api_id":7,
            "api_time":60,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[2,1],
            "api_win_item2":[0,0]
        },
        {
            "api_id":8,
            "api_time":180,
            "api_use_fuel":0.5,
            "api_use_bull":0.2,
            "api_win_item1":[2,2],
            "api_win_item2":[3,1]
        },
        {
            "api_id":9,
            "api_time":240,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[10,1],
            "api_win_item2":[1,2]
        },
        {
            "api_id":10,
            "api_time":90,
            "api_use_fuel":0.3,
            "api_use_bull":0,
            "api_win_item1":[1,1],
            "api_win_item2":[2,1]
        },
        {
            "api_id":11,
            "api_time":300,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[10,1],
            "api_win_item2":[1,1]
        },
        {
            "api_id":12,
            "api_time":480,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[11,1],
            "api_win_item2":[3,1]
        },
        {
            "api_id":13,
            "api_time":240,
            "api_use_fuel":0.5,
            "api_use_bull":0.4,
            "api_win_item1":[1,2],
            "api_win_item2":[10,1]
        },
        {
            "api_id":14,
            "api_time":360,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[1,1],
            "api_win_item2":[3,1]
        },
        {
            "api_id":15,
            "api_time":720,
            "api_use_fuel":0.5,
            "api_use_bull":0.4,
            "api_win_item1":[12,1],
            "api_win_item2":[3,1]
        },
        {
            "api_id":16,
            "api_time":900,
            "api_use_fuel":0.5,
            "api_use_bull":0.4,
            "api_win_item1":[2,2],
            "api_win_item2":[3,2]
        },
        {
            "api_id":17,
            "api_time":45,
            "api_use_fuel":0.3,
            "api_use_bull":0.4,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":18,
            "api_time":300,
            "api_use_fuel":0.5,
            "api_use_bull":0.2,
            "api_win_item1":[1,1],
            "api_win_item2":[0,0]
        },
        {
            "api_id":19,
            "api_time":360,
            "api_use_fuel":0.5,
            "api_use_bull":0.4,
            "api_win_item1":[10,1],
            "api_win_item2":[3,1]
        },
        {
            "api_id":20,
            "api_time":120,
            "api_use_fuel":0.5,
            "api_use_bull":0.4,
            "api_win_item1":[3,1],
            "api_win_item2":[10,1]
        },
        {
            "api_id":21,
            "api_time":140,
            "api_use_fuel":0.8,
            "api_use_bull":0.7,
            "api_win_item1":[10,1],
            "api_win_item2":[0,0]
        },
        {
            "api_id":22,
            "api_time":180,
            "api_use_fuel":0.8,
            "api_use_bull":0.7,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":23,
            "api_time":240,
            "api_use_fuel":0.8,
            "api_use_bull":0.8,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":24,
            "api_time":500,
            "api_use_fuel":0.9,
            "api_use_bull":0.6,
            "api_win_item1":[3,2],
            "api_win_item2":[1,1]
        },
        {
            "api_id":25,
            "api_time":2400,
            "api_use_fuel":0.5,
            "api_use_bull":0.8,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":26,
            "api_time":4800,
            "api_use_fuel":0.8,
            "api_use_bull":0.8,
            "api_win_item1":[1,3],
            "api_win_item2":[0,0]
        },
        {
            "api_id":27,
            "api_time":1200,
            "api_use_fuel":0.8,
            "api_use_bull":0.8,
            "api_win_item1":[3,1],
            "api_win_item2":[10,2]
        },
        {
            "api_id":28,
            "api_time":1500,
            "api_use_fuel":0.8,
            "api_use_bull":0.8,
            "api_win_item1":[3,2],
            "api_win_item2":[11,2]
        },
        {
            "api_id":29,
            "api_time":1440,
            "api_use_fuel":0.9,
            "api_use_bull":0.4,
            "api_win_item1":[3,1],
            "api_win_item2":[10,1]
        },
        {
            "api_id":30,
            "api_time":2880,
            "api_use_fuel":0.9,
            "api_use_bull":0.7,
            "api_win_item1":[3,3],
            "api_win_item2":[0,0]
        },
        {
            "api_id":31,
            "api_time":120,
            "api_use_fuel":0.5,
            "api_use_bull":0,
            "api_win_item1":[10,1],
            "api_win_item2":[0,0],
        },
        {
            "api_id":32,
            "api_time":1440,
            "api_use_fuel":0.9,
            "api_use_bull":0.3,
            "api_win_item1":[12,1],
            "api_win_item2":[3,3]
        },
        {
            "api_id":33,
            "api_time":15,
            "api_use_fuel":0.5,
            "api_use_bull":0.8,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":34,
            "api_time":30,
            "api_use_fuel":0.5,
            "api_use_bull":0.8,
            "api_win_item1":[0,0],
            "api_win_item2":[0,0]
        },
        {
            "api_id":35,
            "api_time":420,
            "api_use_fuel":0.8,
            "api_use_bull":0.8,
            "api_win_item1":[10,2],
            "api_win_item2":[3,1]
        },
        {
            "api_id":36,
            "api_time":540,
            "api_use_fuel":0.8,
            "api_use_bull":0.8,
            "api_win_item1":[11,2],
            "api_win_item2":[1,1]
        },
        {
            "api_id":37,
            "api_time":165,
            "api_use_fuel":0.8,
            "api_use_bull":0.8,
            "api_win_item1":[10,1],
            "api_win_item2":[0,0]
        },
        {
            "api_id":38,
            "api_time":175,
            "api_use_fuel":0.8,
            "api_use_bull":0.8,
            "api_win_item1":[10,1],
            "api_win_item2":[0,0]
        },
        {
            "api_id":39,
            "api_time":1800,
            "api_use_fuel":0.9,
            "api_use_bull":0.9,
            "api_win_item1":[1,2],
            "api_win_item2":[11,1]
        },
        {
            "api_id":40,
            "api_time":410,
            "api_use_fuel":0.8,
            "api_use_bull":0.7,
            "api_win_item1":[10,3],
            "api_win_item2":[1,1]
        }
    ];
