language: node_js
sudo: false
node_js:
  - 0.10
env:
  - PATH=$HOME/purescript:$PATH
install:
  - TAG=v0.7.2.1
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install pulp
  - npm install uglify-js
  - pulp dep install
script:
  - pulp test
