language: node_js
sudo: false
node_js:
  - "5"
env:
  - PATH=$HOME/purescript:$PATH
install:
  - TAG=v0.8.3
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install pulp
  - npm install uglify-js
  - npm install bower
  - npm install benchmark
  - npm install purescript-psa
  - bower install
script:
  - pulp build  --censor-codes=ImplicitImport,HidingImport --censor-lib
  - pulp test
